# Generated by Django 4.1.1 on 2022-09-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section1_heading', models.CharField(blank=True, max_length=50, null=True)),
                ('section1_heading_colored', models.CharField(blank=True, max_length=50, null=True)),
                ('section1_text', models.TextField(blank=True, null=True)),
                ('section1_button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('section1_image', models.ImageField(blank=True, null=True, upload_to='images/home/')),
            ],
        ),
    ]
