# Generated by Django 4.1.1 on 2022-09-12 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_home_options_home_navlink1_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='section1_button_text',
            new_name='slider1_button_text',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='section1_heading',
            new_name='slider1_heading',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='section1_heading_colored',
            new_name='slider1_heading_colored',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='section1_image',
            new_name='slider1_image',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='section1_text',
            new_name='slider1_text',
        ),
    ]
