# Generated by Django 4.1.1 on 2022-09-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_section1_button_text_home_slider1_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='who_we_1_heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='who_we_1_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/home/'),
        ),
        migrations.AddField(
            model_name='home',
            name='who_we_1_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='who_we_2_heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='who_we_2_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/home/'),
        ),
        migrations.AddField(
            model_name='home',
            name='who_we_2_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='who_we_3_heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='who_we_3_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/home/'),
        ),
        migrations.AddField(
            model_name='home',
            name='who_we_3_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='who_we_4_heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='who_we_4_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/home/'),
        ),
        migrations.AddField(
            model_name='home',
            name='who_we_4_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='who_we_5_heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='who_we_5_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/home/'),
        ),
        migrations.AddField(
            model_name='home',
            name='who_we_5_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='who_we_6_heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='who_we_6_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/home/'),
        ),
        migrations.AddField(
            model_name='home',
            name='who_we_6_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
