# Generated by Django 4.1.1 on 2022-09-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_home_small_slider_1_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='info_slider_1_heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='info_slider_1_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/home/'),
        ),
        migrations.AddField(
            model_name='home',
            name='info_slider_1_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='info_slider_1_link_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='info_slider_1_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='info_slider_2_heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='info_slider_2_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/home/'),
        ),
        migrations.AddField(
            model_name='home',
            name='info_slider_2_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='info_slider_2_link_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='info_slider_2_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='info_slider_3_heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='info_slider_3_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/home/'),
        ),
        migrations.AddField(
            model_name='home',
            name='info_slider_3_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='info_slider_3_link_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='info_slider_3_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='info_slider_4_heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='info_slider_4_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/home/'),
        ),
        migrations.AddField(
            model_name='home',
            name='info_slider_4_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='info_slider_4_link_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='info_slider_4_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='info_slider_5_heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='info_slider_5_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/home/'),
        ),
        migrations.AddField(
            model_name='home',
            name='info_slider_5_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='info_slider_5_link_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='info_slider_5_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
