# Generated by Django 4.1.1 on 2022-09-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_home_info_slider_1_heading_home_info_slider_1_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='slider1_button_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
