# Generated by Django 4.1.1 on 2022-09-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_savedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='slider2_button_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='slider2_button_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='slider2_heading',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='slider2_heading_colored',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='slider2_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/home/'),
        ),
        migrations.AddField(
            model_name='home',
            name='slider2_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='slider3_button_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='slider3_button_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='slider3_heading',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='slider3_heading_colored',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='slider3_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/home/'),
        ),
        migrations.AddField(
            model_name='home',
            name='slider3_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
