# Generated by Django 4.1.1 on 2022-09-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_home_slider2_button_text_home_slider2_button_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_text', models.CharField(blank=True, max_length=200, null=True)),
                ('topinfoHeading_r_main', models.CharField(blank=True, max_length=200, null=True)),
                ('sectopinfoHeading_r_sub', models.CharField(blank=True, max_length=200, null=True)),
                ('topinfoHeading_r_topic', models.CharField(blank=True, max_length=200, null=True)),
                ('topinfoHeading_r1', models.CharField(blank=True, max_length=200, null=True)),
                ('r1_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('topinfoHeading_r2', models.CharField(blank=True, max_length=200, null=True)),
                ('r2_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('topinfoHeading_r3', models.URLField(blank=True, null=True)),
                ('r3_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('topinfoHeading_r4', models.CharField(blank=True, max_length=200, null=True)),
                ('r4_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('topinfoHeading_l_main', models.CharField(blank=True, max_length=200, null=True)),
                ('topinfoHeading_l_sub', models.CharField(blank=True, max_length=200, null=True)),
                ('topinfoHeading_l_topic', models.CharField(blank=True, max_length=200, null=True)),
                ('topinfoHeading_l1', models.CharField(blank=True, max_length=200, null=True)),
                ('l1_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('topinfoHeading_l2', models.CharField(blank=True, max_length=200, null=True)),
                ('l2_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('topinfoHeading_l3', models.URLField(blank=True, null=True)),
                ('l3_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('topinfoHeading_l4', models.CharField(blank=True, max_length=200, null=True)),
                ('l4_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('businessModel2_main', models.CharField(blank=True, max_length=200, null=True)),
                ('businessModel2_point1', models.CharField(blank=True, max_length=50, null=True)),
                ('point1_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('businessModel2_point2', models.CharField(blank=True, max_length=50, null=True)),
                ('point2_image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('point2_image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('point2_image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('point2_image4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('point2_image5', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('point2_image6', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('topSpace_heading', models.CharField(blank=True, max_length=50, null=True)),
                ('topSpace_text', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
