# Generated by Django 4.1.1 on 2022-09-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='r1_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='r2_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='r3_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='r4_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
